### ISSUE TITLE
FlinkTypeToType Should Support TimestampType And ZonedTimestampType

### ISSUE THREAD

**Issue by YesOrNo828** [generic-datalake/iceberg-pro#30]
Now FlinkTypeToType support convert **TimestampType** to **Types.TimestampType.withZone()**, but this is a mistake. I think TimestampType should be converted to Types.TimestampType.withoutZone(), and ZonedTimestampType should be converted to Types.TimestampType.withZone().
https://github.com/generic-datalake/iceberg/blob/master/flink/src/main/java/org/apache/iceberg/flink/FlinkTypeToType.java#L133

**Comment by openinx** [comment]
Yes, you're right,  mind to prepare a pull request ?

**Comment by YesOrNo828** [comment]
I will open a pr for this.
